server:
  port: 8080
  servlet:
    context-path: /
#logging:
#  config: classpath:logback.xml
#  level: DEBUG

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/gw?serverTimezone=GMT%2B8
    username: root 
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#日志
#logging:
#  level: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis_config.xml
  type-aliases-package: com.ly.fashionmania.entity
